### ISSUE TITLE
Listener is not working?

### ISSUE THREAD

**Issue by Ciantic** [Grabacr07/VirtualDesktop#1]
I modified the MainWindow.xaml.cs like this:

```
	public MainWindow()
	{
		this.InitializeComponent();
		VirtualDesktop.CurrentChanged += VirtualDesktop_CurrentChanged;
	}

	private void VirtualDesktop_CurrentChanged(object sender, VirtualDesktopChangedEventArgs e)
	{
		Console.WriteLine("CurrentChanged");
	}
```

The program crashes, however if I comment out the `VirtualDesktop.CurrentChanged += VirtualDesktop_CurrentChanged;` it works.

Reason I'm trying this is because I'm testing the notifications on C++ code but there is a input lag if I register a notifications listener from C++. Also the printing does not register. I wonder if the notifications definition given in the Russian cyberforum (which is only reference I could find) is out dated?

**Comment by kelias** [comment]
Doesn't seem to have an issue for me. 

VirtualDesktop.CurrentChanged += (o, e) => Console.WriteLine("CurrentChanged");

Works with no problems on a WPF window like what you have. Do you have the latest code?

**Comment by Ciantic** [comment]
It was Invalid Variant, I disabled that it's now working. I did find another issue I'll open a new item for it.
