### ISSUE TITLE
Support for "Showing window in all desktops" (Win10 anniversary feature)

### ISSUE THREAD

**Issue by Ciantic** [Grabacr07/VirtualDesktop#11]
I found this in the context menu of Windows 10 anniversary edition of the Task View:

![image](https://cloud.githubusercontent.com/assets/64731/17445559/35306c7e-5b4e-11e6-86b1-70c888d1ab17.png)

So I think there is somewhere a way to do this programmatically. I don't know how you got the new GUID (f31574d6-b682-4cdc-bd56-1827860abec6) so I thought you might find a way to access those two new features also.

**Comment by Ciantic** [comment]
Btw, I think @Grabacr07 has already implemented this in develop branch, it's called pinned apps or some such.

**Comment by Grabacr07** [comment]
I implemented these features.
You can check this in the VirtualDesktop.Showcase project.

![gif](https://cloud.githubusercontent.com/assets/1779073/17458193/86289528-5c45-11e6-90ac-26c783a9d168.gif)

**Comment by Grabacr07** [comment]
@Ciantic
I hope I've assisted in some way.
https://github.com/Ciantic/VirtualDesktopAccessor/issues/9

**Comment by Ciantic** [comment]
yes, your code made it to work. I still have no idea where the interface definitions are pulled, I suppose one could reverse engineer them from the Windows DLL's. Is that how you found out the IVirtualManagerInternal definition? 

Other one for instance is this: IApplicationViewCollection, Google finds one obscure entry. It's definition only exists in your code and in that obscure site.
