### ISSUE TITLE
Invalid Variant

### ISSUE THREAD

**Issue by kelias** [Grabacr07/VirtualDesktop#2]
Getting the error:

"Additional information: An invalid VARIANT was detected during a conversion from an unmanaged VARIANT to a managed object. Passing invalid VARIANTs to the CLR can cause unexpected exceptions, corruption or data loss"

Obviously I can turn that off so it doesn't appear, but I'm not sure the impact of ignoring it.

https://msdn.microsoft.com/en-us/library/7zw2e2w7(v=vs.110).aspx

Can be reproduced by going to Debug\Exceptions in the menu.
Expand Managed Debugging Assistants
Check Thrown under "InvalidVariant"

Then do something like this:
VirtualDesktop.CurrentChanged += (o, e) =>  Console.WriteLine("test");

And it usually pops up immediately, or right after to switch desktops.

**Comment by kelias** [comment]
This seems to be from the VirtualDesktop.static.notification RegisterListner method, when the service.Register() method is called.

**Comment by tmyt** [comment]
The problem solved by PR #7.
