### ISSUE TITLE
Add Ability to Get List of Pinned Windows & Pinned Applications

### ISSUE THREAD

**Issue by mzomparelli** [Grabacr07/VirtualDesktop#24]
I'm not sure if this is possible, but I would like to build a list of which windows are pinned and which applications are pinned.

**Comment by ericnewton76** [comment]
How does one pin an application?  Looks like an interesting feature I didnt know about.

**Comment by mzomparelli** [comment]
You can Pin a window or you can Pin an app. See my app that uses this API. On my main page I explain pin app and window.

https://github.com/mzomparelli/zVirtualDesktop

**Comment by mzomparelli** [comment]
What is the difference between pin app and pin window?
An easy way to imagine this is if you use pin window on a chrome browser window, only that window will be visible on all desktops. Any other chrome windows would stay on a single desktop. If you were to pin application on a chrome window then all chrome windows would show up on all desktops. This includes new chrome windows.

**Comment by mzomparelli** [comment]
I have concluded that it is the responsibility of the program that is consuming this project to manage which windows are pinned. Thus, I am closing this issue.
