### ISSUE TITLE
[Request] Nuget Package(s)

### ISSUE THREAD

**Issue by GeorgeHahn** [Grabacr07/VirtualDesktop#4]
Hi! Wonderful library, thanks for sharing it! I'm using it to switch desktops using hand gestures (via a Leap Motion). This library saved me a ton of research, I really appreciate it!

It would be nice if it were available on NuGet for ease of use and additional discoverability.

**Comment by Grabacr07** [comment]
Thank you for your interest!

I published a library on nuget.
Following packages become available.
https://www.nuget.org/packages/VirtualDesktop/
https://www.nuget.org/packages/VirtualDesktop.WPF/
https://www.nuget.org/packages/VirtualDesktop.WinForms/

**Comment by GeorgeHahn** [comment]
Spectacular! Thanks again!
