### ISSUE TITLE
VirtualDesktop FromHwnd(IntPtr hWnd) Exception

### ISSUE THREAD

**Issue by wil70** [Grabacr07/VirtualDesktop#42]
When I start a new application (like Chrome) and ask for its desktop (via VirtualDesktop FromHwnd(IntPtr hWnd)), then I get the following exception:
{"Element not found. (Exception from HRESULT: 0x8002802B (TYPE_E_ELEMENTNOTFOUND))"}

If I click one the application that I just started and then call again "VirtualDesktop FromHwnd(IntPtr hWnd) " then I do get an exception and the function works well..

Any idea?

Thanks!

**Comment by rhyek** [comment]
Why was this closed?
