### ISSUE TITLE
WinUI 3 and .NET 5

### ISSUE THREAD

**Issue by Slion** [Grabacr07/VirtualDesktop#64]
Is there a version for WinUI?

**Comment by Grabacr07** [comment]
Please set your project's target framework to `net6.0-windows10.0.19041.0`, it should work with WinUI 3.

If you need .NET 5 version, set the VirtualDesktop target to `net5.0-windows10.0.19041.0` and add `<LangVersion>10.0</LangVersion>` to make it work.

**Comment by Slion** [comment]
Using the main NuGet package?

**Comment by Grabacr07** [comment]
How to get the HWND (window handle; IntPtr) in WinUI 3?

> at WindowsDesktop.Interop.Build10240.ApplicationViewCollection.GetViewForHwnd(IntPtr hWnd)
> Message=Element not found. (0x8002802B (TYPE_E_ELEMENTNOTFOUND))

This means that the specified window cannot be found.

**Comment by Slion** [comment]
> How to get the HWND (window handle; IntPtr) in WinUI 3?

`WinRT.Interop.WindowNative.GetWindowHandle(this)` I know my HWND is valid I'm using it to do a bunch of other stuff and it works.

**Comment by Slion** [comment]
> If `VirtualDesktop.CurrentChanged` is not fired, try accessing other static members. I think it will not work just subscribe to the event, since the internal initialization is triggered by the static method/property access.
> 
> e.g.
> 
> ```
> var current = VirtualDesktop.Current;
> ```

That did the trick, thanks.

**Comment by Slion** [comment]
> This means that the specified window cannot be found.

I could get it working by delaying the `PinWindow` call until the first window Activated event is fired. If I do it from the window constructor it won't work though the HWND is already valid it's probably not registered yet a desktop window somehow.

Thanks for the amazing support @Grabacr07 ❤🎉 Looks like I'm all set!
