### ISSUE TITLE
Desktop name is empty

### ISSUE THREAD

**Issue by Slion** [Grabacr07/VirtualDesktop#65]
I tried using the desktop name from the current desktop and from the new desktop upon `CurrentChanged` event but both return empty strings.

**Comment by Slion** [comment]
Also my app is now showing the following characters as window title:
![image](https://user-images.githubusercontent.com/6508892/152662737-aa730532-80a3-4826-82fd-02e2a805c6c4.png)
Is this caused by this library somehow?

**Comment by Slion** [comment]
> Is this caused by this library somehow?

No, it's not, looks like a nasty Windows bug of some sort… unrelated it seems. Hope there is nothing offending in those characters.

**Comment by Grabacr07** [comment]
Windows 10 does not support getting names and wallpapers, so you need to use Windows 11.
If you cannot get the name on Windows 11, please let me know.

**Comment by Slion** [comment]
> No, it's not, looks like a nasty Windows bug of some sort… unrelated it seems. Hope there is nothing offending in those characters.

Cause of that issue is explained there: https://github.com/microsoft/CsWin32/issues/343#issuecomment-1030805845
