### ISSUE TITLE
Virtual desktop is null of msedge and notepad++

### ISSUE THREAD

**Issue by Taster-git** [Grabacr07/VirtualDesktop#77]
I am getting Virtual Desktop of each running process (by handles) by Using Windows APIs and following code snippet.

```
List<IntPtr> handles = GetWindowsHandles();

foreach (var hWnd in handles)
{
VirtualDesktop Virtual_Desktop = VirtualDesktop.FromHwnd(hWnd);
}
```

But when handle of Msedge and Notepad++ is passed to this method, Virtual Desktop is null.

**Comment by Dexterously** [comment]
It might be how you're getting the "GetWindowsHandles()"

Try showing me that code.

It could also be that msedge and notepad++ are set to show on all desktops.

**Comment by Taster-git** [comment]
> It might be how you're getting the "GetWindowsHandles()"
> 
> Try showing me that code.
> 
> It could also be that msedge and notepad++ are set to show on all desktops.

Yes you are on Right. Both applications are Pinned. So that why Virtual desktop is null. I have read documentation. Thanks for your reply.
