### ISSUE TITLE
Problem with Windows 11 22H2

### ISSUE THREAD

**Issue by ZhulaiIvan** [Grabacr07/VirtualDesktop#78]
Hi.
I have this error after appearing an application with VirtualDesktop. 
What I must do to resolve it?
![image](https://user-images.githubusercontent.com/47326203/193523352-8af47c1b-c6cd-4846-8035-f5813eb516f6.png)

**Comment by anortham** [comment]
Same, something has changed in 22H2.

**Comment by merken** [comment]
Same here, such a pity!
