### ISSUE TITLE
IVirtualDesktopManagerInternal instance not returned; get null instead

### ISSUE THREAD

**Issue by cspotcode** [Grabacr07/VirtualDesktop#9]
When attempting to get instance of `IVirtualDesktopManagerInternal`, I get null. (verified in the debugger)

https://github.com/Grabacr07/VirtualDesktop/blob/master/source/VirtualDesktop/Interop/VirtualDesktopInteropHelper.cs#L26

I'm running Windows 10 Pro Insider Preview, Build 14372.rs1_release.160620-2342.  This error didn't occur until I installed the Insider Preview, so hopefully it will resolve itself when the "Anniversary Update" is released in August.

**Comment by Ciantic** [comment]
Looks like the MIDL_INTERFACE (AF8DA486-95BB-4460-B3B7-6E7A6B2962B5) for the IVirtualDesktopManagerInternal has changed with latest Insider, I looked with hex editor the file twinui.dll, from the old I can find it (search for 6E7A6B2962B5), but in new one it must have changed.

I haven't figured out how to determine what is the new GUID.

**Comment by cspotcode** [comment]
I think the author has addressed this in the develop branch.

Check out the changes here: https://github.com/Grabacr07/VirtualDesktop/commit/7fc13e094dbdf6c0fd26c506c7bcc793e8d28b87

I pulled them into my project and it seems to have fixed the problem.

**Comment by Ciantic** [comment]
I wonder how @Grabacr07 found out the new GUID, "f31574d6-b682-4cdc-bd56-1827860abec6", it would be interesting knowledge.

**Comment by Grabacr07** [comment]
Sorry for not replying earlier.

It is so simple.
I found the new IID by searching in the Registry Editor.

<img width="688" alt="ss160807023137ls" src="https://cloud.githubusercontent.com/assets/1779073/17458257/269943a8-5c47-11e6-9afb-a439fbd596fa.png">
